resolver: lts-7.19

packages:
- '.'

extra-deps:
- optparse-applicative-0.13.1.0
- connection-0.2.7
- monad-loops-0.4.3
- bytestring-show-0.3.5.6
- network-fancy-0.2.4
- attoparsec-0.13.1.0

flags: {}

extra-package-dbs: []

nix:
  enable: true
  packages: []
