resolver: lts-7.19

packages:
- '.'

extra-deps:
- optparse-applicative-0.13.1.0
- connection-0.2.7
- attoparsec-0.13.1.0
- monad-loops-0.4.3
- uuid-1.3.13

flags: {}

extra-package-dbs: []

nix:
  enable: true
  packages: []
