resolver: lts-8.5

packages:
- '.'

extra-deps:
- profunctors-5.2
- newtype-generics-0.5
- optparse-applicative-0.13.1.0
- connection-0.2.7
- attoparsec-0.13.1.0
- monad-loops-0.4.3
- uuid-1.3.13
- http-conduit-2.2.3.1
- http-client-0.5.6.1
- http-client-tls-0.3.4
- regex-pcre-0.94.4
- html-entities-1.1.3
- hlint-1.9.41

flags: {}

extra-package-dbs: []

nix:
  enable: true
  packages: [zlib pcre]
